#+title: My Emacs configuration

#  LocalWords:  emacs-lisp

This repository is my literate Emacs configuration. My uses for Emacs center around:
+ Prose writing.
+ Note-taking.
+ Developing small elisp packages.
My configuration is tailored to achieve these ends, also taking into account my personal tastes and preferences. Additionally, I semi-frequently build from the master branch of Emacs, so my configuration may include settings to options not packaged in officially released Emacs versions yet.

If you have any questions about my configuration or would like to discuss anything related to this configuration or Emacs, feel free to reach out by email: krisbalintona@gmail.com.

* Directories

Several subdirectories are relevant herein:
+ modules/
  - Personal configuration files.
  - Where I place ~(use-package ...)~ declarations.
+ lisp/
  - Personal elisp code I've spun into separate files that act as libraries.
  - Several of these files are candidates for packages.
+ etc/
  - The ~no-littering-etc-directory~. The directory where packages place their configuration files.
+ var/
  - The ~no-littering-var-directory~. The directory where packages place their persistent data files.
  - Not included (tracked) in this repository.
All emacs-lisp files are the result of tangling the =emacs-config.org= file (i.e. calling ~org-babel-tangle~, or =C-c C-v t=).

* A note to visitors

I often make commits to this repository, whether very minor tweaks or sweeping changes. As such, expect the commit history to be messy: I do not feel the need to strongly impose version control conventions intended for open source projects. Nevertheless, I do try to maintain a certain degree of cleanliness.
