;; -*- coding: utf-8; lexical-binding: t -*-
(define-abbrev-table 'emacs-lisp-mode-abbrev-table
  '(
    ("Anathology" "Anthology" nil :count 0)
    ("Disregad" "Disregard" nil :count 0)
    ("Emptry" "Empty" nil :count 0)
    ("Otheriwse" "Otherwise" nil :count 0)
    ("Preceeding" "Preceding" nil :count 0)
    ("Swicth" "Switch" nil :count 0)
    ("Timesttamps" "Timestamps" nil :count 0)
    ("accomodate" "accommodate" nil :count 0)
    ("appropraite" "appropriate" nil :count 0)
    ("becareful" "be careful" nil :count 0)
    ("behavioe" "behavior" nil :count 0)
    ("chnages" "changes" nil :count 0)
    ("compatability" "compatibility" nil :count 0)
    ("dupliccates" "duplicates" nil :count 0)
    ("easiser" "easier" nil :count 0)
    ("ellilpsis" "ellipsis" nil :count 0)
    ("exhaustve" "exhaustive" nil :count 0)
    ("grammers" "grammars" nil :count 0)
    ("headling" "heading" nil :count 1)
    ("inheritted" "inherited" nil :count 0)
    ("innaccessible" "inaccessible" nil :count 0)
    ("internall" "internally" nil :count 0)
    ("laoded" "loaded" nil :count 0)
    ("ommitted" "omitted" nil :count 0)
    ("parameer" "parameter" nil :count 0)
    ("proparty" "property" nil :count 0)
    ("properies" "properties" nil :count 0)
    ("properites" "properties" nil :count 0)
    ("quiting" "quitting" nil :count 0)
    ("resuls" "results" nil :count 0)
    ("tempaltes" "templates" nil :count 0)
    ("unconditionnally" "unconditionally" nil :count 0)
   ))

(define-abbrev-table 'log-edit-mode-abbrev-table
  '(
    ("Defne" "Define" nil :count 0)
    ("Erroroneous" "Erroneous" nil :count 0)
    ("Insstall" "Install" nil :count 0)
    ("enancements" "enhancements" nil :count 0)
    ("obscelete" "obsolete" nil :count 0)
    ("obscoleting" "obsoleting" nil :count 0)
    ("ommitted" "omitted" nil :count 0)
   ))

(define-abbrev-table 'markdown-mode-abbrev-table
  '(
    ("adminstration" "administration" nil :count 0)
    ("automic" "automatic" nil :count 0)
    ("commiting" "committing" nil :count 0)
    ("mayer" "mayor" nil :count 0)
    ("mneumonic" "mnemonic" nil :count 0)
    ("traffick" "traffic" nil :count 0)
    ("traumatizedand" "traumatized" nil :count 0)
   ))

(define-abbrev-table 'notmuch-message-mode-abbrev-table
  '(
    ("Additionaly" "Additionally" nil :count 0)
    ("againt" "against" nil :count 0)
    ("apolgoize" "apologize" nil :count 0)
    ("dispay" "display" nil :count 0)
    ("establshing" "establishing" nil :count 0)
    ("exhausive" "exhaustive" nil :count 0)
    ("hygenic" "hygienic" nil :count 0)
    ("meantioned" "mentioned" nil :count 0)
    ("noticable" "noticeable" nil :count 0)
    ("obscolete" "obsolete" nil :count 0)
    ("opporutnity" "opportunity" nil :count 0)
    ("partcipate" "participate" nil :count 0)
    ("possibilties" "possibilities" nil :count 0)
    ("propogation" "propagation" nil :count 0)
    ("runnin" "running" nil :count 0)
    ("speficiation" "specification" nil :count 0)
    ("sufficies" "suffices" nil :count 0)
   ))

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("ANdoird-specific" "Android-specific" nil :count 0)
    ("Adminstrative" "Administrative" nil :count 0)
    ("Barteby" "Bartleby" nil :count 0)
    ("Boredem" "Boredom" nil :count 0)
    ("Brazillian" "Brazilian" nil :count 0)
    ("Chiling" "Chilling" nil :count 0)
    ("Discplinary" "Disciplinary" nil :count 0)
    ("Epiaode" "Episode" nil :count 0)
    ("Happipness" "Happiness" nil :count 0)
    ("Innoculation" "Inoculation" nil :count 0)
    ("Laclhan" "Lachlan" nil :count 0)
    ("Likewisefor" "Likewise for" nil :count 0)
    ("Metaphyscs" "Metaphysics" nil :count 0)
    ("PlayStore" "Play Store" nil :count 0)
    ("Predesination" "Predestination" nil :count 0)
    ("Refernces" "References" nil :count 0)
    ("Scaret" "Scarlet" nil :count 0)
    ("THe" "The" nil :count 7)
    ("Targetted" "Targeted" nil :count 0)
    ("Unfortuantely" "Unfortunately" nil :count 0)
    ("Wawtched" "Watched" nil :count 0)
    ("Wishlist" "Wish list" nil :count 0)
    ("Woulldn't" "Wouldn't" nil :count 0)
    ("Zetelkasten" "Zettelkasten" nil :count 0)
    ("abnoxiously" "obnoxiously" nil :count 0)
    ("aburpt" "abrupt" nil :count 0)
    ("accomlish" "accomplish" nil :count 0)
    ("activites" "activities" nil :count 0)
    ("aeriel" "aerial" nil :count 1)
    ("aftewards" "afterwards" nil :count 0)
    ("algorithmicly" "algorithmic" nil :count 0)
    ("amongst" "among" nil :count 1)
    ("amputatino" "amputation" nil :count 0)
    ("apartmnets" "apartments" nil :count 0)
    ("apocolypse" "apocalypse" nil :count 1)
    ("appearnce" "appearance" nil :count 0)
    ("assertability" "assertibility" nil :count 0)
    ("atittude" "attitude" nil :count 0)
    ("availalble" "available" nil :count 0)
    ("backround" "background" nil :count 0)
    ("backstepping" "back-stepping" nil :count 0)
    ("balanaces" "balances" nil :count 0)
    ("barelly" "barely" nil :count 0)
    ("becasue" "because" nil :count 0)
    ("beginniner" "beginner" nil :count 0)
    ("bellieve" "believe" nil :count 0)
    ("brillient" "brilliant" nil :count 0)
    ("bufferfly" "butterfly" nil :count 0)
    ("buildling" "building" nil :count 1)
    ("cacophanous" "cacophonous" nil :count 0)
    ("cannibalising" "cannibalizing" nil :count 0)
    ("chaaracterization" "characterization" nil :count 0)
    ("characteres" "characters" nil :count 1)
    ("cinematoography" "cinematography" nil :count 0)
    ("cleaniness" "cleanliness" nil :count 0)
    ("comfident" "confident" nil :count 0)
    ("commonpeople" "common people" nil :count 0)
    ("compatabiity" "compatibility" nil :count 0)
    ("comptent" "competent" nil :count 0)
    ("confuct" "conduct" nil :count 0)
    ("conscsiousness" "consciousness" nil :count 0)
    ("controling" "controlling" nil :count 0)
    ("conveniencec" "convenience" nil :count 0)
    ("cooky" "kooky" nil :count 0)
    ("couldnt" "couldn't" nil :count 0)
    ("countour" "contour" nil :count 0)
    ("critiqal" "critical" nil :count 0)
    ("crystalize" "crystallize" nil :count 0)
    ("damange" "damage" nil :count 0)
    ("dangeous" "dangerous" nil :count 0)
    ("dediccatoin" "dedication" nil :count 0)
    ("descendent" "descendant" nil :count 0)
    ("desparately" "desperately" nil :count 0)
    ("deveopment" "development" nil :count 0)
    ("devestated" "devastated" nil :count 0)
    ("devestating" "devastating" nil :count 0)
    ("dialgoue" "dialogue" nil :count 0)
    ("differneitation" "differentiation" nil :count 0)
    ("digitial" "digital" nil :count 0)
    ("discoverd" "discovered" nil :count 2)
    ("edicice" "edifice" nil :count 0)
    ("enchancing" "enhancing" nil :count 0)
    ("encounterd" "encountered" nil :count 0)
    ("entaglements" "entanglements" nil :count 0)
    ("everthing" "everything" nil :count 0)
    ("exhahstion" "exhaustion" nil :count 0)
    ("exhausive" "exhaustive" nil :count 0)
    ("exisstence" "existence" nil :count 0)
    ("expeirence" "experience" nil :count 0)
    ("experinced" "experienced" nil :count 0)
    ("expsnive" "expensive" nil :count 0)
    ("familities" "families" nil :count 0)
    ("fealing" "feeling" nil :count 0)
    ("fhe" "the" nil :count 0)
    ("filesystem" "file-system" nil :count 0)
    ("flambuoyant" "flamboyant" nil :count 0)
    ("fleeieng" "fleeing" nil :count 0)
    ("fo" "of" nil :count 8)
    ("folowing" "following" nil :count 0)
    ("forumla" "formula" nil :count 0)
    ("framentation" "fragmentation" nil :count 0)
    ("functionialities" "functionalities" nil :count 0)
    ("fundamnetally" "fundamentally" nil :count 0)
    ("girst" "first" nil :count 0)
    ("guillitine" "guillotine" nil :count 0)
    ("guillitines" "guillotines" nil :count 0)
    ("guillitone" "guillotine" nil :count 0)
    ("guilotine" "guillotine" nil :count 0)
    ("happend" "happened" nil :count 0)
    ("happenkng" "happening" nil :count 0)
    ("himsefl" "himself" nil :count 0)
    ("hoome" "home" nil :count 0)
    ("iddeal" "ideal" nil :count 0)
    ("importnat" "important" nil :count 0)
    ("incease" "increase" nil :count 0)
    ("inconsitencies" "inconsistencies" nil :count 0)
    ("indepently" "independently" nil :count 0)
    ("indispensible" "indispensable" nil :count 0)
    ("indistinguishavle" "indistinguishable" nil :count 0)
    ("initiaiating" "initiating" nil :count 0)
    ("insuration" "insurance" nil :count 0)
    ("intentionaity" "intentionality" nil :count 0)
    ("intercations" "interactions" nil :count 0)
    ("interseting" "interesting" nil :count 0)
    ("intriguie" "intrigue" nil :count 0)
    ("inviible" "invisible" nil :count 0)
    ("iself" "itself" nil :count 0)
    ("isntead" "instead" nil :count 0)
    ("kidns" "kinds" nil :count 0)
    ("labelled" "labeled" nil :count 0)
    ("lablled" "labeled" nil :count 0)
    ("learnign" "learning" nil :count 0)
    ("legnth" "length" nil :count 0)
    ("likeable" "likable" nil :count 1)
    ("llmight" "might" nil :count 0)
    ("machinary" "machinery" nil :count 0)
    ("maintanence" "maintenance" nil :count 0)
    ("manufactor" "manufacture" nil :count 0)
    ("mentioend" "mentioned" nil :count 0)
    ("metaphyics" "metaphysics" nil :count 0)
    ("milllion" "million" nil :count 0)
    ("miltary" "military" nil :count 0)
    ("minimalistic" "minimalist" nil :count 0)
    ("minutae" "minutiae" nil :count 0)
    ("mistimecd" "mistimed" nil :count 0)
    ("modifer" "modifier" nil :count 0)
    ("musr" "must" nil :count 0)
    ("niffty" "nifty" nil :count 0)
    ("noticably" "noticeably" nil :count 0)
    ("ommitted" "omitted" nil :count 0)
    ("oponents" "opponents" nil :count 0)
    ("orginary" "ordinary" nil :count 0)
    ("otherhand" "other hand" nil :count 0)
    ("overriden" "overridden" nil :count 0)
    ("pallete" "palette" nil :count 0)
    ("pallette" "palette" nil :count 0)
    ("peopel" "people" nil :count 0)
    ("pereson" "person" nil :count 0)
    ("personell" "personnel" nil :count 0)
    ("phenomenogical" "phenomenological" nil :count 0)
    ("philosphers" "philosophers" nil :count 0)
    ("picutre" "picture" nil :count 0)
    ("plothole" "plot hole" nil :count 0)
    ("poitns" "points" nil :count 0)
    ("positon" "position" nil :count 0)
    ("possibiities" "possibilities" nil :count 0)
    ("possibiltiies" "possibilities" nil :count 0)
    ("prepatory" "preparatory" nil :count 0)
    ("prescence" "presence" nil :count 1)
    ("prioriteis" "priorities" nil :count 0)
    ("probaby" "probably" nil :count 0)
    ("projcect" "project" nil :count 0)
    ("proofound" "profound" nil :count 0)
    ("propery" "property" nil :count 0)
    ("psitioing" "positioning" nil :count 0)
    ("pummelling" "pummeling" nil :count 1)
    ("rachet" "ratchet" nil :count 0)
    ("raiting" "rating" nil :count 0)
    ("recordkeeping" "record-keeping" nil :count 0)
    ("recuring" "recurring" nil :count 0)
    ("reflecions" "reflections" nil :count 0)
    ("regading" "regarding" nil :count 0)
    ("repalce" "replace" nil :count 0)
    ("repetitiotns" "repetitions" nil :count 0)
    ("reseting" "resetting" nil :count 0)
    ("respnoses" "responses" nil :count 0)
    ("respnosible" "responsible" nil :count 0)
    ("responbility" "responsibility" nil :count 0)
    ("responsibilties" "responsibilities" nil :count 0)
    ("reuinion" "reunion" nil :count 0)
    ("reuinte" "reunite" nil :count 2)
    ("reuinting" "reuinion" nil :count 0)
    ("reuninting" "reunion" nil :count 0)
    ("roels" "roles" nil :count 0)
    ("rollling" "rolling" nil :count 0)
    ("russian" "Russian" nil :count 1)
    ("sacrifes" "sacrifices" nil :count 0)
    ("sacrified" "sacrificed" nil :count 0)
    ("sacrifies" "sacrifices" nil :count 0)
    ("sandox" "sandbox" nil :count 0)
    ("sems" "seems" nil :count 0)
    ("sharepn" "sharpen" nil :count 0)
    ("sharpenning" "sharpening" nil :count 0)
    ("signifncant" "significant" nil :count 0)
    ("sillhouettes" "silhouettes" nil :count 0)
    ("slef" "self" nil :count 0)
    ("socioeconmic" "socioeconomic" nil :count 0)
    ("solidifed" "solidified" nil :count 0)
    ("sovreign" "sovereign" nil :count 0)
    ("spreedshteet" "spreadsheet" nil :count 0)
    ("stablized" "stabilized" nil :count 0)
    ("standup" "stand-up" nil :count 0)
    ("stubborness" "stubbornness" nil :count 0)
    ("subltely" "subtly" nil :count 0)
    ("subltle" "subtle" nil :count 0)
    ("suiteable" "suitable" nil :count 0)
    ("supercede" "supersede" nil :count 0)
    ("superceded" "superseded" nil :count 0)
    ("sutained" "sustained" nil :count 0)
    ("symption" "symptom" nil :count 0)
    ("syption" "symption" nil :count 0)
    ("systemazing" "systematizing" nil :count 0)
    ("tabulaed" "tabulated" nil :count 0)
    ("tatoo" "tattoo" nil :count 0)
    ("telivised" "televised" nil :count 0)
    ("their's" "theirs" nil :count 0)
    ("their’s" "theirs" nil :count 0)
    ("thereffter" "thereafter" nil :count 0)
    ("thnk" "think" nil :count 0)
    ("thoerize" "theorize" nil :count 0)
    ("thsi" "this" nil :count 0)
    ("travelled" "traveled" nil :count 1)
    ("turmoi" "turmoil" nil :count 0)
    ("unpleasnat" "unpleasant" nil :count 0)
    ("unsecure" "unsecured" nil :count 0)
    ("utlize" "utilize" nil :count 0)
    ("verbage" "verbiage" nil :count 0)
    ("verus" "versus" nil :count 0)
    ("whenver" "whenever" nil :count 0)
    ("worldbuilding" "world-building" nil :count 0)
    ("woudn't" "wouldn't" nil :count 0)
    ("wrtite" "write" nil :count 0)
    ("yourhips" "your hips" nil :count 0)
    ("zipline" "zip-line" nil :count 0)
   ))

(define-abbrev-table 'scheme-mode-abbrev-table
  '(
    ("preferrable" "preferable" nil :count 0)
   ))

(define-abbrev-table 'sh-mode-abbrev-table
  '(
    ("Bootstrappping" "Bootstrapping" nil :count 0)
    ("structire" "structure" nil :count 0)
   ))

