;;-*-coding: utf-8;-*-
(define-abbrev-table 'emacs-lisp-mode-abbrev-table
  '(
    ("Ovverride" "Override" nil :count 0)
    ("compatability" "comparability" nil :count 0)
    ("couterpart" "counterpart" nil :count 0)
    ("devault" "default" nil :count 0)
    ("fasater" "faster" nil :count 0)
    ("preferrable" "preferable" nil :count 0)
    ("proeprty" "property" nil :count 0)
    ("versison" "version" nil :count 0)
   ))

(define-abbrev-table 'global-abbrev-table
  '(
    (";d" "" krisb-abbrev-current-date :count 25)
    (";t" "" krisb-abbrev-todo-keyword :count 0)
    (";td" "" krisb-abbrev-todo-keyword-and-date :count 1)
   ))

(define-abbrev-table 'notmuch-message-mode-abbrev-table
  '(
    ("positoin" "position" nil :count 0)
   ))

(define-abbrev-table 'org-mode-abbrev-table
  '(
    ("Adivse" "Advise" nil :count 0)
    ("Colordo" "Colorado" nil :count 0)
    ("Dumpng" "Dumping" nil :count 0)
    ("Emaill" "Email" nil :count 0)
    ("Keybinds" "Keybindings" nil :count 1)
    ("Luhamnn" "Luhmann" nil :count 2)
    ("Marketting" "Marketing" nil :count 0)
    ("Nietzche" "Nietzsche" nil :count 0)
    ("Phillipines" "Philippines" nil :count 0)
    ("Poitn" "Point" nil :count 0)
    ("Tenessee" "Tennessee" nil :count 0)
    ("Zetetlkasten" "Zettelkasten" nil :count 0)
    ("antagonoist" "antagonist" nil :count 0)
    ("beheve" "behave" nil :count 0)
    ("bookpages" "book pages" nil :count 0)
    ("canstration" "castration" nil :count 0)
    ("catalogy" "catalog" nil :count 0)
    ("coleagues" "colleagues" nil :count 0)
    ("collaborive" "collaborative" nil :count 0)
    ("compatability" "compatibility" nil :count 0)
    ("concent" "content" nil :count 0)
    ("concpet" "concept" nil :count 0)
    ("concusion" "conclusion" nil :count 0)
    ("develoepd" "developed" nil :count 0)
    ("direcctly" "directly" nil :count 0)
    ("disambiguiate" "disambiguate" nil :count 0)
    ("easiliy" "easily" nil :count 0)
    ("engangement" "engagement" nil :count 0)
    ("enuciated" "enunciated" nil :count 0)
    ("excusive" "exclusive" nil :count 0)
    ("expoired" "expired" nil :count 0)
    ("fractical" "fractal" nil :count 0)
    ("heirarchical" "hierarchical" nil :count 0)
    ("heirarhcy" "hierarchy" nil :count 0)
    ("incompability" "incompatibility" nil :count 0)
    ("indepedently" "independently" nil :count 0)
    ("invidual" "individual" nil :count 0)
    ("itnroduces" "introduces" nil :count 0)
    ("keywods" "keywords" nil :count 0)
    ("labelled" "labeled" nil :count 0)
    ("lughter" "laughter" nil :count 0)
    ("maintanence" "maintenance" nil :count 0)
    ("maleability" "malleability" nil :count 0)
    ("misperceives" "misconceives" nil :count 0)
    ("mw" "me" nil :count 0)
    ("obiously" "obviously" nil :count 0)
    ("ommitted" "omitted" nil :count 0)
    ("otheres" "others" nil :count 0)
    ("particularlly" "particularly" nil :count 0)
    ("ponderingon" "pondering on" nil :count 0)
    ("practioners" "practitioners" nil :count 0)
    ("privvty" "privy" nil :count 0)
    ("proeprty" "property" nil :count 0)
    ("realizng" "realizing" nil :count 0)
    ("recommendatiosn" "recommendations" nil :count 0)
    ("repicate" "replicate" nil :count 0)
    ("resolvese" "resolves" nil :count 0)
    ("searcing" "searching" nil :count 0)
    ("signalign" "signaling" nil :count 0)
    ("slipboxes" "slip-boxes" nil :count 2)
    ("standardzed" "standardized" nil :count 0)
    ("stimualtes" "stimulates" nil :count 0)
    ("stornger" "stronger" nil :count 0)
    ("supercede" "supersede" nil :count 0)
    ("superceded" "superseded" nil :count 0)
    ("supercedes" "supersedes" nil :count 0)
    ("symolibc" "symbolic" nil :count 0)
    ("thaat" "that" nil :count 0)
    ("thinknig" "thinking" nil :count 0)
    ("travelling" "traveling" nil :count 0)
    ("underneat" "underneath" nil :count 1)
   ))

(define-abbrev-table 'text-mode-abbrev-table
  '(
    ("Remoov" "Remove" nil :count 0)
    ("hugo" "Hugo" nil :count 17)
    ("isntances" "instances" nil :count 0)
    ("isntead" "instead" nil :count 0)
    ("reposotiry" "repository" nil :count 0)
   ))

(define-abbrev-table 'vc-git-log-edit-mode-abbrev-table
  '(
    ("accomodate" "accommodate" nil :count 0)
    ("activaate" "activate" nil :count 0)
    ("caled" "called" nil :count 0)
    ("ccommands" "commands" nil :count 0)
    ("disacrd" "discard" nil :count 0)
    ("exectuable" "executable" nil :count 0)
    ("immediaetely" "immediately" nil :count 0)
    ("intersting" "interesting" nil :count 0)
    ("slightlyg" "slightly" nil :count 0)
    ("subdirecotry" "subdirectory" nil :count 0)
    ("visibitilty" "visibility" nil :count 0)
   ))

