
;; ----- amx-history -----
(
 hide-mode-line-mode
 org-mode-restart
 customize-group
 company-box-mode
 global-company-mode
 counsel-buffer-or-recentf
 whitespace-cleanup
)

;; ----- amx-data -----
(
 (customize-group . 8)
 (pdf-tools-install . 1)
 (load-file . 2)
 (counsel-load-library . 2)
 (explain-pause-top . 3)
 (selectrum-mode . 2)
 (orb-note-actions . 1)
 (kill-this-buffer . 1)
 (evil-org-beginning-of-line . 1)
 (garbage-collect . 6)
 (powerthesaurus-lookup-word . 2)
 (straight-use-package . 1)
 (langtool-check . 2)
 (langtool-correct-buffer . 1)
 (langtool-check-done . 1)
 (explain-pause-mode . 2)
 (calendar . 1)
 (counsel-imenu . 1)
 (org-tree-to-indirect-buffer . 1)
 (lexic-search . 1)
 (lexic-search-word-at-point . 2)
 (company-diag . 3)
 (global-company-mode . 22)
 (counsel-describe-face . 1)
 (company-box-mode . 29)
 (smartparens-mode . 4)
 (show-smartparens-mode . 3)
 (all-the-icons-install-fonts . 1)
 (lisp-extra-font-lock-mode . 4)
 (rainbow-delimiters-mode . 2)
 (beacon-mode . 2)
 (global-eldoc-mode . 2)
 (rename-file . 1)
 (helm-recentf . 2)
 (helm-mini . 2)
 (helm-browse-project . 3)
 (helm-projects-find-files . 2)
 (org-mode-restart . 3)
 (helm-minibuffer-history . 1)
 (helm-find-files . 3)
 (find-file . 2)
 (golden-ratio-mode . 6)
 (windmove-right . 1)
 (windmove-left . 1)
 (read-only-mode . 1)
 (describe-keymap . 1)
 (downcase-word . 1)
 (org-noter-kill-session . 3)
 (company-tng-configure-default . 1)
 (company-tng-mode . 1)
 (global-auto-revert-mode . 2)
 (git-gutter-mode . 2)
 (global-git-gutter-mode . 1)
 (highlight-function-calls-mode . 1)
 (helm-M-x . 1)
 (helm-occur . 1)
 (helm-apropos . 1)
 (counsel-apropos . 2)
 (helm-imenu . 1)
 (helm-swoop . 5)
 (helm-multi-files . 1)
 (helm-multi-swoop . 1)
 (helm-swoop-from-isearch . 1)
 (evil-motion-state . 1)
 (evil-first-non-blank . 1)
 (ace-jump-mode . 2)
 (ace-jump-move . 1)
 (evil-ace-jump-char-mode . 1)
 (ace-jump-line-mode . 2)
 (whitespace-cleanup . 1)
 (counsel-buffer-or-recentf . 1)
 (hide-mode-line-mode . 2)
)
