
;; ----- amx-history -----
(
 keyfreq-html
 keyfreq-html-v2
 customize-group
 selectrum-mode
 wikinforg
 ivy-mode
 company-box-mode
)

;; ----- amx-data -----
(
 (customize-group . 13)
 (pdf-tools-install . 1)
 (load-file . 2)
 (counsel-load-library . 4)
 (explain-pause-top . 3)
 (selectrum-mode . 4)
 (orb-note-actions . 1)
 (kill-this-buffer . 1)
 (evil-org-beginning-of-line . 1)
 (garbage-collect . 6)
 (powerthesaurus-lookup-word . 2)
 (straight-use-package . 1)
 (langtool-check . 2)
 (langtool-correct-buffer . 1)
 (langtool-check-done . 1)
 (explain-pause-mode . 2)
 (calendar . 1)
 (counsel-imenu . 1)
 (org-tree-to-indirect-buffer . 1)
 (lexic-search . 1)
 (lexic-search-word-at-point . 2)
 (company-diag . 5)
 (global-company-mode . 22)
 (counsel-describe-face . 2)
 (company-box-mode . 35)
 (smartparens-mode . 4)
 (show-smartparens-mode . 3)
 (all-the-icons-install-fonts . 1)
 (lisp-extra-font-lock-mode . 4)
 (rainbow-delimiters-mode . 2)
 (beacon-mode . 2)
 (global-eldoc-mode . 2)
 (rename-file . 1)
 (helm-recentf . 2)
 (helm-mini . 2)
 (helm-browse-project . 3)
 (helm-projects-find-files . 5)
 (org-mode-restart . 26)
 (helm-minibuffer-history . 1)
 (helm-find-files . 3)
 (find-file . 4)
 (golden-ratio-mode . 6)
 (windmove-right . 1)
 (windmove-left . 1)
 (read-only-mode . 1)
 (describe-keymap . 2)
 (downcase-word . 1)
 (org-noter-kill-session . 4)
 (company-tng-configure-default . 1)
 (company-tng-mode . 1)
 (global-auto-revert-mode . 2)
 (git-gutter-mode . 2)
 (global-git-gutter-mode . 1)
 (highlight-function-calls-mode . 1)
 (helm-M-x . 1)
 (helm-occur . 1)
 (helm-apropos . 1)
 (counsel-apropos . 2)
 (helm-imenu . 1)
 (helm-swoop . 5)
 (helm-multi-files . 1)
 (helm-multi-swoop . 1)
 (helm-swoop-from-isearch . 1)
 (evil-motion-state . 1)
 (evil-first-non-blank . 1)
 (ace-jump-mode . 2)
 (ace-jump-move . 1)
 (evil-ace-jump-char-mode . 1)
 (ace-jump-line-mode . 2)
 (whitespace-cleanup . 1)
 (counsel-buffer-or-recentf . 1)
 (hide-mode-line-mode . 2)
 (align-entire . 1)
 (evil-align-right . 1)
 (align-regexp . 1)
 (mouse-avoidance-mode . 1)
 (selectrum-helm-mode . 4)
 (modify-face . 1)
 (counsel-rg . 1)
 (selectrum-rg . 2)
 (helm-projectile-on . 1)
 (helm-projectile-find-file . 2)
 (projectile-global-mode . 1)
 (esup . 1)
 (flyspell-mode . 1)
 (artbollocks-count-words . 1)
 (artbollocks-mode . 5)
 (writegood-mode . 1)
 (writegood-grade-level . 1)
 (writegood-reading-ease . 1)
 (helm-projectile-switch-to-buffer . 2)
 (helm-projectile-rg . 7)
 (helm-projectile-switch-project . 1)
 (counsel-fonts . 12)
 (describe-char . 4)
 (doom-modeline-mode . 4)
 (find-library . 1)
 (make-empty-file . 1)
 (latex-preview-pane-mode . 33)
 (org-copy-subtree . 1)
 (imenu-add-menubar-index . 2)
 (LaTeX-mode . 2)
 (latex-mode . 2)
 (next-error . 1)
 (counsel-yank-pop . 2)
 (pdf-view-mode . 1)
 (company-org-block . 2)
 (wikinforg . 4)
 (ivy-mode . 4)
 (keyfreq-html-v2 . 1)
 (keyfreq-html . 1)
)
