;;; Automatically generated by ‘recentf’ on Sun Nov  1 20:51:45 2020.

(setq recentf-list
      '(
        "/home/krisbalintona/main-emacs/configs/second-brain.org"
        "/home/krisbalintona/Documents/org-database/roam/Oct312020-140749-whitelusiadscanto.org"
        "/home/krisbalintona/Documents/org-database/agenda/inbox.org"
        "/home/krisbalintona/qmk_firmware/keyboards/kbdfans/kbd4x/keymaps/my-programmed-keymap/tapdance.c"
        "/home/krisbalintona/main-emacs/configs/evil-packages.org"
        "/home/krisbalintona/Documents/org-database/roam/Oct292020-130117.org"
        "/home/krisbalintona/Documents/Emails/Queue/cur/2020-11-01_19:12:46_1"
        "/home/krisbalintona/qmk_firmware/keyboards/kbdfans/kbd4x/keymaps/my-programmed-keymap/keymap.c"
        "/home/krisbalintona/main-emacs/configs/base-config.org"
        "/home/krisbalintona/main-emacs/configs/shell.org"
        "/home/krisbalintona/main-emacs/configs/completion-frameworks.org"
        "/home/krisbalintona/main-emacs/straight/build/golden-ratio/golden-ratio-autoloads.el"
        "/home/krisbalintona/main-emacs/elisp/better-defaults-rcp.el"
        "/home/krisbalintona/main-emacs/elisp/straight-package-management-rcp.el"
        ))

(setq recentf-filter-changer-current 'nil)


;; Local Variables:
;; coding: utf-8-emacs
;; End:
