;;; -*- coding: utf-8; mode: lisp-data -*-
(("/home/krisbalintona/.orhc-bibtex-cache" . 20796)
 ("/home/krisbalintona/.doom.d/"
  (dired-filename . "/home/krisbalintona/.doom.d/.."))
 ("/home/krisbalintona/Desktop/"
  (dired-filename . "/home/krisbalintona/Desktop/brave-gmhpgfbjacdocjngbdbmhkgcpochhnge-Default.desktop"))
 ("/home/krisbalintona/Cloned_Repos/"
  (dired-filename . "/home/krisbalintona/Cloned_Repos/.."))
 ("/home/krisbalintona/"
  (dired-filename . "/home/krisbalintona/.electron-gyp"))
 ("/home/krisbalintona/__MACOSX/"
  (dired-filename . "/home/krisbalintona/__MACOSX/._20200622 - IMF v3"))
 ("/home/krisbalintona/.icons/"
  (dired-filename . "/home/krisbalintona/.icons/default"))
 ("/home/krisbalintona/Documents/Zotero/"
  (dired-filename . "/home/krisbalintona/Documents/Zotero/tmp"))
 ("/home/krisbalintona/zsh/"
  (dired-filename . "/home/krisbalintona/zsh/.zshrc"))
 ("/home/krisbalintona/.config/dconf/"
  (dired-filename . "/home/krisbalintona/.config/dconf/.."))
 ("/home/krisbalintona/.config/"
  (dired-filename . "/home/krisbalintona/.config/yay"))
 ("/home/krisbalintona/.config/yay/" . 217)
 ("/home/krisbalintona/.config/autostart-scripts/" . 231)
 ("/home/krisbalintona/.config/lutris/"
  (dired-filename . "/home/krisbalintona/.config/lutris/lutris.conf"))
 ("/home/krisbalintona/.config/pulse/"
  (dired-filename . "/home/krisbalintona/.config/pulse/310100d360014ad18a467d50b83670dc-card-database.tdb"))
 ("/home/krisbalintona/.config/gtk-2.0/"
  (dired-filename . "/home/krisbalintona/.config/gtk-2.0/gtkfilechooser.ini"))
 ("/home/krisbalintona/.config/Optimus Manager/"
  (dired-filename . "/home/krisbalintona/.config/Optimus Manager/Optimus Manager Qt.conf"))
 ("/home/krisbalintona/.config/rclone/"
  (dired-filename . "/home/krisbalintona/.config/rclone/rclone.conf"))
 ("/home/krisbalintona/.config/light/" . 219)
 ("/home/krisbalintona/.config/qmk/"
  (dired-filename . "/home/krisbalintona/.config/qmk/qmk.ini"))
 ("/home/krisbalintona/.config/rofi/"
  (dired-filename . "/home/krisbalintona/.config/rofi/themes"))
 ("/home/krisbalintona/.config/rofi/themes/"
  (dired-filename . "/home/krisbalintona/.config/rofi/themes/apps.rasi"))
 ("/home/krisbalintona/.config/libvirt/"
  (dired-filename . "/home/krisbalintona/.config/libvirt/qemu"))
 ("/home/krisbalintona/.config/polybar/"
  (dired-filename . "/home/krisbalintona/.config/polybar/config"))
 ("/home/krisbalintona/.config/kitty/"
  (dired-filename . "/home/krisbalintona/.config/kitty/kitty.conf"))
 ("/home/krisbalintona/.config/i3/"
  (dired-filename . "/home/krisbalintona/.config/i3/config"))
 ("/home/krisbalintona/.config/deadd/"
  (dired-filename . "/home/krisbalintona/.config/deadd/deadd.conf"))
 ("/home/krisbalintona/.config/gtk-3.0/"
  (dired-filename . "/home/krisbalintona/.config/gtk-3.0/.."))
 ("/home/krisbalintona/.config/xob/" . 292)
 ("/home/krisbalintona/.config/obs-studio/"
  (dired-filename . "/home/krisbalintona/.config/obs-studio/basic"))
 ("/home/krisbalintona/.config/gconf/" . 219)
 ("/home/krisbalintona/.config/nvim/"
  (dired-filename . "/home/krisbalintona/.config/nvim/autoload"))
 ("/home/krisbalintona/.config/thefuck/"
  (dired-filename . "/home/krisbalintona/.config/thefuck/__pycache__"))
 ("/home/krisbalintona/.config/autostart/"
  (dired-filename . "/home/krisbalintona/.config/autostart/copyq.desktop"))
 ("/home/krisbalintona/.config/Mathpix/"
  (dired-filename . "/home/krisbalintona/.config/Mathpix/Mathpix Snipping Tool.conf"))
 ("/home/krisbalintona/.config/nemo/"
  (dired-filename . "/home/krisbalintona/.config/nemo/bookmark-metadata"))
 ("/home/krisbalintona/.config/fcitx/"
  (dired-filename . "/home/krisbalintona/.config/fcitx/cached_layout"))
 ("/home/krisbalintona/.config/flameshot/"
  (dired-filename . "/home/krisbalintona/.config/flameshot/flameshot.ini"))
 ("/home/krisbalintona/.TabNine/"
  (dired-filename . "/home/krisbalintona/.TabNine/3.1.1"))
 ("/home/krisbalintona/.ssh/"
  (dired-filename . "/home/krisbalintona/.ssh/id_ed25519"))
 ("/home/krisbalintona/.offlineimap/"
  (dired-filename . "/home/krisbalintona/.offlineimap/Account-Brown"))
 ("/home/krisbalintona/.offlineimap/Account-Brown/"
  (dired-filename . "/home/krisbalintona/.offlineimap/Account-Brown/LocalStatus-sqlite"))
 ("/home/krisbalintona/.gnupg/"
  (dired-filename . "/home/krisbalintona/.gnupg/crls.d"))
 ("/home/krisbalintona/gnupg-backup.tar" . 49)
 ("/home/krisbalintona/Games/"
  (dired-filename . "/home/krisbalintona/Games/league-of-legends"))
 ("/home/krisbalintona/Games/league-of-legends/"
  (dired-filename . "/home/krisbalintona/Games/league-of-legends/dosdevices"))
 ("/home/krisbalintona/.w3m/" . 205)
 ("/home/krisbalintona/.vim/"
  (dired-filename . "/home/krisbalintona/.vim/.netrwhist"))
 ("/home/krisbalintona/.pki/"
  (dired-filename . "/home/krisbalintona/.pki/nssdb"))
 ("/home/krisbalintona/.nv/"
  (dired-filename . "/home/krisbalintona/.nv/ComputeCache"))
 ("/home/krisbalintona/.mume/"
  (dired-filename . "/home/krisbalintona/.mume/config.json"))
 ("/home/krisbalintona/.gem/"
  (dired-filename . "/home/krisbalintona/.gem/ruby"))
 ("/home/krisbalintona/doom-emacs/"
  (dired-filename . "/home/krisbalintona/doom-emacs/bin"))
 ("/home/krisbalintona/.cache/"
  (dired-filename . "/home/krisbalintona/.cache/node-gyp"))
 ("/home/krisbalintona/Documents/org-database/agenda/archive.org" . 338099)
 ("/home/krisbalintona/Documents/org-database/roam/seedbox.org" . 98)
 ("/home/krisbalintona/Documents/org-database/roam/Sep282020-1141.org" . 410)
 ("/home/krisbalintona/Documents/org-database/roam/Sep272020-2215.org" . 1047)
 ("/home/krisbalintona/Documents/org-database/roam/Sep272020-2148.org" . 990)
 ("/home/krisbalintona/Documents/org-database/roam/Sep272020-2141.org" . 1242)
 ("/home/krisbalintona/Documents/org-database/roam/Sep272020-2137.org" . 1000)
 ("/home/krisbalintona/Documents/org-database/roam/Sep272020-2122.org" . 848)
 ("/home/krisbalintona/Documents/org-database/roam/Sep272020-2120.org" . 875)
 ("/home/krisbalintona/Documents/org-database/roam/Sep272020-2057.org" . 1285)
 ("/home/krisbalintona/Documents/org-database/roam/Sep272020-2027.org" . 669)
 ("/home/krisbalintona/Documents/org-database/roam/Sep262020-1801.org" . 915)
 ("/home/krisbalintona/Documents/org-database/roam/Sep262020-1725.org" . 226)
 ("/home/krisbalintona/Documents/org-database/roam/Sep222020-1812.org" . 664)
 ("/home/krisbalintona/Documents/org-database/roam/Sep222020-1731.org" . 405)
 ("/home/krisbalintona/Documents/org-database/roam/Sep212020-1409.org" . 657)
 ("/home/krisbalintona/Documents/org-database/roam/Sep172020-2220.org" . 907)
 ("/home/krisbalintona/Documents/org-database/roam/Sep162020-2152-aristotlemetaphysics.org" . 7129)
 ("/home/krisbalintona/Documents/org-database/roam/Sep142020-1409.org" . 146)
 ("/home/krisbalintona/Documents/org-database/roam/Sep102020-0318-irvinghistorylifevoyages1828.org" . 12041)
 ("/home/krisbalintona/Documents/org-database/roam/Oct312020-140749-whitelusiadscanto.org" . 2736)
 ("/home/krisbalintona/Documents/org-database/roam/Oct312020-140603-pigafettafirstvoyageworld.org" . 442)
 ("/home/krisbalintona/Documents/org-database/roam/Oct292020-130117.org" . 21938)
 ("/home/krisbalintona/Documents/org-database/roam/Oct292020-125345-caminhaletterperovaz.org" . 1172)
 ("/home/krisbalintona/Documents/org-database/roam/Oct282020-203047.org" . 2091)
 ("/home/krisbalintona/Documents/org-database/roam/Oct282020-195200.org" . 225)
 ("/home/krisbalintona/Documents/org-database/roam/Oct282020-194839.org" . 1118)
 ("/home/krisbalintona/Documents/org-database/roam/Oct282020-192725.org" . 489)
 ("/home/krisbalintona/Documents/org-database/roam/Oct272020-140529.org" . 36)
 ("/home/krisbalintona/Documents/org-database/roam/Oct252020-044957.org" . 599)
 ("/home/krisbalintona/Documents/org-database/roam/Oct252020-043115.org" . 656)
 ("/home/krisbalintona/Documents/org-database/roam/Oct242020-234949.org" . 691)
 ("/home/krisbalintona/Documents/org-database/roam/Oct242020-034959-hookyaassciencemanuelinestyle.org" . 388)
 ("/home/krisbalintona/Documents/org-database/roam/Oct242020-030215-pintogasparfrutuosoportuguese2003.org" . 371)
 ("/home/krisbalintona/Documents/org-database/roam/Oct232020-193527-ortaconversationssimplesdrugs.org" . 488)
 ("/home/krisbalintona/Documents/org-database/roam/Oct222020-185344.org" . 876)
 ("/home/krisbalintona/Documents/org-database/roam/Oct212020-194244.org" . 1009)
 ("/home/krisbalintona/Documents/org-database/roam/Oct212020-185746.org" . 1317)
 ("/home/krisbalintona/Documents/org-database/roam/Oct212020-183324.org" . 246)
 ("/home/krisbalintona/Documents/org-database/roam/Oct212020-160505.org" . 393)
 ("/home/krisbalintona/Documents/org-database/roam/Oct212020-000115.org" . 1132)
 ("/home/krisbalintona/Documents/org-database/roam/Oct202020-235308.org" . 234)
 ("/home/krisbalintona/Documents/org-database/roam/Oct192020-140309.org" . 7660)
 ("/home/krisbalintona/Documents/org-database/roam/Oct192020-000704.org" . 21)
 ("/home/krisbalintona/Documents/org-database/roam/Oct142020-200938-dominguessciencetechnologyportuguese.org" . 2085)
 ("/home/krisbalintona/Documents/org-database/roam/Oct142020-1904-pereiraesmeraldosituorbis2010.org" . 322)
 ("/home/krisbalintona/Documents/org-database/roam/Oct142020-014949.org" . 1854)
 ("/home/krisbalintona/Documents/org-database/roam/Oct132020-2212-somervilleriseearlyconstitution1892.org" . 18445)
 ("/home/krisbalintona/Documents/org-database/roam/Oct132020-1917.org" . 139)
 ("/home/krisbalintona/Documents/org-database/roam/Oct132020-1357.org" . 297)
 ("/home/krisbalintona/Documents/org-database/roam/Oct132020-0155.org" . 10)
 ("/home/krisbalintona/Documents/org-database/roam/Oct122020-1846.org" . 440)
 ("/home/krisbalintona/Documents/org-database/roam/Oct122020-1821.org" . 451)
 ("/home/krisbalintona/Documents/org-database/roam/Oct122020-1622.org" . 912)
 ("/home/krisbalintona/Documents/org-database/roam/Oct122020-1616.org" . 28)
 ("/home/krisbalintona/Documents/org-database/roam/Oct112020-2208.org" . 322)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-1742.org" . 658)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-1559.org" . 637)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-1553.org" . 237)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-1544.org" . 42)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-1532.org" . 251)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-1522.org" . 464)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-1520.org" . 212)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-1504.org" . 250)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-1500.org" . 235)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-0040.org" . 234)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-0028.org" . 674)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-0023.org" . 466)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-0021.org" . 428)
 ("/home/krisbalintona/Documents/org-database/roam/Oct102020-0008.org" . 280)
 ("/home/krisbalintona/Documents/org-database/roam/Oct092020-2323.org" . 677)
 ("/home/krisbalintona/Documents/org-database/roam/Oct092020-2254.org" . 1052)
 ("/home/krisbalintona/Documents/org-database/roam/Oct092020-2235.org" . 609)
 ("/home/krisbalintona/Documents/org-database/roam/Oct092020-2216.org" . 174)
 ("/home/krisbalintona/Documents/org-database/roam/Oct092020-2215.org" . 549)
 ("/home/krisbalintona/Documents/org-database/roam/Oct092020-2209.org" . 212)
 ("/home/krisbalintona/Documents/org-database/roam/Oct092020-2201.org" . 853)
 ("/home/krisbalintona/Documents/org-database/roam/Oct072020-1732.org" . 336)
 ("/home/krisbalintona/Documents/org-database/roam/Oct072020-1724.org" . 375)
 ("/home/krisbalintona/Documents/org-database/roam/Oct072020-1703.org" . 420)
 ("/home/krisbalintona/Documents/org-database/roam/Oct072020-1645.org" . 392)
 ("/home/krisbalintona/Documents/org-database/roam/Oct062020-2356.org" . 325)
 ("/home/krisbalintona/Documents/org-database/roam/Oct062020-2321.org" . 425)
 ("/home/krisbalintona/Documents/org-database/roam/Oct062020-1439-rodriguespioneersglobalization2007.org" . 446)
 ("/home/krisbalintona/Documents/org-database/roam/Oct062020-1436-diffiefoundationsportugueseempire1977.org" . 681)
 ("/home/krisbalintona/Documents/org-database/roam/Oct062020-1212-haskinsriseuniversities1957.org" . 4220)
 ("/home/krisbalintona/Documents/org-database/roam/Oct052020-1357.org" . 4502)
 ("/home/krisbalintona/Documents/org-database/roam/Nov302020-223130.org" . 332)
 ("/home/krisbalintona/Documents/org-database/roam/Nov282020-041035-pinchpuritanismrisemodern1992.org" . 843)
 ("/home/krisbalintona/Documents/org-database/roam/Nov272020-193138.org" . 689)
 ("/home/krisbalintona/Documents/org-database/roam/Nov272020-192400.org" . 543)
 ("/home/krisbalintona/Documents/org-database/roam/Nov272020-190946.org" . 232)
 ("/home/krisbalintona/Documents/org-database/roam/Nov232020-140429.org" . 3245)
 ("/home/krisbalintona/Documents/org-database/roam/Nov222020-211434-machiavelliprince.org" . 10170)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-211741.org" . 709)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-210318.org" . 909)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-202841.org" . 453)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-202051.org" . 280)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-193815.org" . 221)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-192547.org" . 154)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-184532.org" . 898)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-182053.org" . 777)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-180131.org" . 300)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-135755.org" . 380)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-135322.org" . 33)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-132116.org" . 173)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-132015.org" . 295)
 ("/home/krisbalintona/Documents/org-database/roam/Nov202020-124937.org" . 137)
 ("/home/krisbalintona/Documents/org-database/roam/Nov192020-012534.org" . 446)
 ("/home/krisbalintona/Documents/org-database/roam/Nov192020-010928.org" . 315)
 ("/home/krisbalintona/Documents/org-database/roam/Nov192020-005604.org" . 219)
 ("/home/krisbalintona/Documents/org-database/roam/Nov182020-175746-capponiunlikelyprincelife2010.org" . 6208)
 ("/home/krisbalintona/Documents/org-database/roam/Nov172020-175430-mansfieldniccolomachiavellibiography.org" . 1972)
 ("/home/krisbalintona/Documents/org-database/roam/Nov172020-175224.org" . 21756)
 ("/home/krisbalintona/Documents/org-database/roam/Nov162020-140231.org" . 4623)
 ("/home/krisbalintona/Documents/org-database/roam/Nov152020-194150.org" . 120)
 ("/home/krisbalintona/Documents/org-database/roam/Nov122020-225649.org" . 38)
 ("/home/krisbalintona/Documents/org-database/roam/Nov122020-223843.org" . 36)
 ("/home/krisbalintona/Documents/org-database/roam/Nov122020-215604-brownuniversitysteeringcommitteeonslaveryandjusticeslaveryjustice2006.org" . 7169)
 ("/home/krisbalintona/Documents/org-database/roam/Nov092020-132109.org" . 3221)
 ("/home/krisbalintona/Documents/org-database/roam/Nov082020-180120.org" . 731)
 ("/home/krisbalintona/Documents/org-database/roam/Nov072020-234159.org" . 751)
 ("/home/krisbalintona/Documents/org-database/roam/Nov042020-174841-cipollagunssailsempires.org" . 6691)
 ("/home/krisbalintona/Documents/org-database/roam/Nov032020-200511.org" . 556)
 ("/home/krisbalintona/Documents/org-database/roam/Nov022020-133341.org" . 2272)
 ("/home/krisbalintona/Documents/org-database/roam/Dec052020-194730.org" . 773)
 ("/home/krisbalintona/Documents/org-database/roam/Dec052020-014943.org" . 585)
 ("/home/krisbalintona/Documents/org-database/roam/Dec042020-123423-corviIntroductionThoughtKarl2014.org" . 6700)
 ("/home/krisbalintona/Documents/org-database/roam/Dec032020-212009.org" . 8127)
 ("/home/krisbalintona/Documents/org-database/roam/Dec022020-010901-fergusoninfluencemachiavellifrancis1944.org" . 8442)
 ("/home/krisbalintona/Documents/org-database/library/transcript-drjinjing_lin.org" . 683)
 ("/home/krisbalintona/Documents/org-database/library/interview-jingjing-lin.org" . 2745)
 ("/home/krisbalintona/Documents/org-database/library/critical-reviews.org" . 1386)
 ("/home/krisbalintona/Documents/org-database/library/brown-interviews-meeting-notes.org" . 3380)
 ("/home/krisbalintona/Documents/org-database/library/POBS0910-research-list.org" . 1205)
 ("/home/krisbalintona/Documents/org-database/agenda/school.org" . 2778)
 ("/home/krisbalintona/Documents/org-database/agenda/misc.org" . 1204)
 ("/home/krisbalintona/Documents/org-database/agenda/media.org" . 1860)
 ("/home/krisbalintona/Documents/org-database/agenda/inputs.org" . 6499)
 ("/home/krisbalintona/Documents/org-database/agenda/inbox.org" . 652)
 ("/home/krisbalintona/Documents/org-database/agenda/housekeeping.org" . 585)
 ("/home/krisbalintona/Documents/org-database/agenda/hobbies.org" . 20732)
 ("/home/krisbalintona/Documents/org-database/agenda/habits.org" . 87)
 ("/home/krisbalintona/.mbsyncrc" . 1613)
 ("/home/krisbalintona/.config/awesome/themes/powerarrow-dark/"
  (dired-filename . "/home/krisbalintona/.config/awesome/themes/powerarrow-dark/theme.lua"))
 ("/home/krisbalintona/dotfiles/i3/.config/i3/config" . 1621)
 ("/home/krisbalintona/main-emacs/elisp/mu4e-rcp.el" . 306)
 ("/home/krisbalintona/.config/awesome/themes/powerarrow-dark/theme.lua" . 583)
 ("/home/krisbalintona/.emacs.d/"
  (dired-filename . "/home/krisbalintona/.emacs.d/.."))
 ("/home/krisbalintona/dotfiles/misc/qmk_firmware/keyboards/kbdfans/kbd4x/keymaps/my-programmed-keymap/keymap.c" . 1542)
 ("/home/krisbalintona/.msmtprc" . 303)
 ("/home/krisbalintona/dotfiles/awesomewm/.config/awesome/rc.lua" . 4660)
 ("/home/krisbalintona/Documents/org-database/roam/index.org" . 374)
 ("/home/krisbalintona/Documents/org-database/library/system-wide-package-groups.org" . 3092)
 ("/home/krisbalintona/.config/rofi/config.rasi" . 143)
 ("/home/krisbalintona/dotfiles/misc/.config/mimeapps.list" . 109)
 ("/home/krisbalintona/qmk_firmware/keyboards/kbdfans/kbd4x/keymaps/my-programmed-keymap/keymap.c" . 1542)
 ("/home/krisbalintona/.xinitrc" . 815)
 ("/home/krisbalintona/.xprofile" . 230)
 ("/home/krisbalintona/main-emacs/straight/build/good-scroll/good-scroll-autoloads.el" . 1120)
 ("/home/krisbalintona/main-emacs/straight/build/org-plus-contrib/org-loaddefs.el" . 114879)
 ("/home/krisbalintona/main-emacs/straight/build/org/org-autoloads.el" . 23111)
 ("/home/krisbalintona/main-emacs/straight/build/lsp-mode/lsp-mode-autoloads.el" . 16831)
 ("/home/krisbalintona/main-emacs/straight/build/org-roam/org-roam-autoloads.el" . 8740)
 ("/home/krisbalintona/main-emacs/straight/build/evil-collection/evil-collection-autoloads.el" . 3029)
 ("/home/krisbalintona/main-emacs/straight/repos/embark/embark.el" . 61788)
 ("/home/krisbalintona/main-emacs/configs/qol-packages.org" . 141)
 ("/home/krisbalintona/main-emacs/elisp/completion-selectrum-rcp.el" . 6604)
 ("/home/krisbalintona/main-emacs/init.el" . 2347)
 ("/home/krisbalintona/main-emacs/straight/build/marginalia/marginalia-autoloads.el" . 1437)
 ("/home/krisbalintona/main-emacs/straight/build/selectrum/selectrum-autoloads.el" . 6965)
 ("/home/krisbalintona/main-emacs/straight/repos/org/lisp/org-loaddefs.el" . 111235)
 ("/home/krisbalintona/main-emacs/elisp/programming-profiling-and-debug-rcp.el" . 381)
 ("/home/krisbalintona/main-emacs/elisp/programming-elisp-rcp.el" . 830)
 ("/home/krisbalintona/main-emacs/elisp/system-variables-rcp.el" . 1426)
 ("/home/krisbalintona/main-emacs/configs/second-brain.org" . 15766)
 ("/home/krisbalintona/main-emacs/elisp/checking-spelling-rcp.el" . 1794)
 ("/home/krisbalintona/main-emacs/elisp/checking-grammar-rcp.el" . 549)
 ("/usr/share/emacs/site-lisp/mu4e/org-mu4e.el" . 9406)
 (#("/sudo:root@PuddingMachine:/usr/share/emacs/site-lisp/mu4e/org-mu4e.el" 6 10
    (tramp-default t)
    11 25
    (tramp-default t))
  . 446)
 ("/usr/share/emacs/site-lisp/mu4e/mu4e-org.el" . 5750)
 (#("/sudo:root@PuddingMachine:/usr/share/emacs/site-lisp/mu4e/mu4e-org.el" 6 10
    (tramp-default t)
    11 25
    (tramp-default t))
  . 307)
 ("/home/krisbalintona/main-emacs/configs/etc-config.org" . 5391)
 ("/home/krisbalintona/main-emacs/elisp/better-defaults-rcp.el" . 4109)
 ("/home/krisbalintona/main-emacs/straight/repos/org-msg/org-msg.el" . 5781)
 ("/home/krisbalintona/main-emacs/elisp/programming-general-rcp.el" . 246)
 ("/home/krisbalintona/main-emacs/elisp/checking-words-rcp.el" . 233)
 ("/home/krisbalintona/main-emacs/elisp/shell-eshell-rcp.el" . 234)
 ("/home/krisbalintona/main-emacs/elisp/programming-lua-rcp.el" . 258)
 ("/home/krisbalintona/main-emacs/elisp/completion-company-rcp.el" . 587)
 ("/home/krisbalintona/main-emacs/elisp/early-packages-rcp.el" . 1895)
 ("/home/krisbalintona/main-emacs/elisp/themes-rcp.el" . 2063)
 ("/home/krisbalintona/main-emacs/elisp/shell-vterm-rcp.el" . 355)
 ("/home/krisbalintona/main-emacs/configs/latex.org" . 328)
 ("/usr/share/emacs/site-lisp/mu4e/mu4e-vars.el" . 7662)
 ("/usr/share/emacs/site-lisp/mu4e/mu4e-context.el" . 1173)
 ("/usr/share/emacs/28.0.50/lisp/server.el" . 6919)
 ("/usr/share/emacs/28.0.50/lisp/time.el" . 5167)
 ("/usr/share/emacs/site-lisp/mu4e/mu4e-compose.el" . 3189)
 ("/usr/share/emacs/28.0.50/lisp/gnus/message.el" . 31641)
 ("/usr/share/emacs/28.0.50/lisp/mail/flow-fill.el" . 2200)
 ("/usr/share/emacs/site-lisp/mu4e/mu4e-draft.el" . 1166)
 ("/usr/share/emacs/28.0.50/lisp/mail/sendmail.el" . 1354)
 ("/usr/share/emacs/28.0.50/lisp/mail/smtpmail.el" . 3020)
 ("/usr/share/emacs/site-lisp/mu4e/mu4e-view.el" . 1805)
 ("/home/krisbalintona/main-emacs/straight/build/mu4e-views/mu4e-views-autoloads.el" . 3878)
 ("/home/krisbalintona/main-emacs/straight/build/xwidgets-reuse/xwidgets-reuse-autoloads.el" . 1077)
 ("/usr/share/emacs/site-lisp/mu4e/mu4e-message.el" . 1151)
 ("/home/krisbalintona/main-emacs/history" . 196)
 ("/home/krisbalintona/main-emacs/straight/build/dash/dash-autoloads.el" . 393)
 ("/home/krisbalintona/main-emacs/straight/repos/synosaurus/synosaurus.el" . 2022)
 ("/home/krisbalintona/main-emacs/straight/build/synosaurus/synosaurus-autoloads.el" . 2342)
 ("/home/krisbalintona/main-emacs/straight/repos/system-packages/system-packages.el" . 13357)
 ("/home/krisbalintona/main-emacs/straight/repos/company-mode/company.el" . 32291)
 ("/home/krisbalintona/main-emacs/straight/build/wordnut/wordnut-autoloads.el" . 857)
 ("/home/krisbalintona/main-emacs/data/"
  (dired-filename . "/home/krisbalintona/main-emacs/data/.."))
 ("/home/krisbalintona/main-emacs/"
  (dired-filename . "/home/krisbalintona/main-emacs/var"))
 ("/home/krisbalintona/main-emacs/var/"
  (dired-filename . "/home/krisbalintona/main-emacs/var/undo-fu-session"))
 ("/home/krisbalintona/main-emacs/var/undo-fu-session/"
  (dired-filename . "/home/krisbalintona/main-emacs/var/undo-fu-session/%2Fhome%2Fkrisbalintona%2FDocuments%2Forg-database%2Fagenda%2Fhobbies.org.gz"))
 ("/home/krisbalintona/main-emacs/straight/repos/doom-modeline/doom-modeline-segments.el" . 58322)
 ("/home/krisbalintona/main-emacs/elisp/evil-rcp.el" . 2624)
 ("/home/krisbalintona/main-emacs/elisp/use-package-rcp.el" . 312)
 ("/home/krisbalintona/main-emacs/elisp/straight-package-management-rcp.el" . 644)
 ("/home/krisbalintona/main-emacs/elisp/auto-gc-rcp.el" . 764)
 ("/home/krisbalintona/main-emacs/elisp/faces-rcp.el" . 1511)
 ("/home/krisbalintona/main-emacs/elisp/custom-directories-rcp.el" . 813)
 ("/home/krisbalintona/main-emacs/elisp/convenient-functions-rcp.el" . 1638)
 ("/home/krisbalintona/main-emacs/elisp/completion-general-rcp.el" . 965)
 ("/home/krisbalintona/main-emacs/elisp/completion-helm-rcp.el" . 2348)
 ("/home/krisbalintona/main-emacs/elisp/undoing-rcp.el" . 282)
 ("/home/krisbalintona/main-emacs/elisp/keybinds-frameworks-rcp.el" . 4812)
 ("/home/krisbalintona/main-emacs/elisp/completion-ivy-rcp.el" . 6354)
 ("/home/krisbalintona/main-emacs/elisp/buffer-and-window-management-rcp.el" . 2316)
 ("/usr/share/emacs/28.0.50/lisp/frame.el" . 6485)
 ("/usr/share/emacs/28.0.50/lisp/recentf.el" . 1465)
 ("/home/krisbalintona/main-emacs/straight/build/use-package-ensure-system-package/use-package-ensure-system-package-autoloads.el" . 831)
 ("/home/krisbalintona/main-emacs/data/custom.el" . 28372)
 ("/home/krisbalintona/main-emacs/straight/repos/evil-collection/modes/outline/evil-collection-outline.el" . 1103)
 ("/home/krisbalintona/main-emacs/straight/repos/evil-collection/modes/company/evil-collection-company.el" . 1570)
 ("/home/krisbalintona/main-emacs/straight/build/auto-compile/auto-compile-autoloads.el" . 5383)
 ("/home/krisbalintona/main-emacs/straight/build/packed/packed-autoloads.el" . 234)
 ("/home/krisbalintona/main-emacs/straight/build/bufler/bufler-autoloads.el" . 932)
 ("/home/krisbalintona/main-emacs/straight/build/magit-section/magit-section-autoloads.el" . 304)
 ("/home/krisbalintona/main-emacs/straight/repos/shackle/shackle.el" . 1325)
 ("/home/krisbalintona/main-emacs/straight/repos/no-littering/no-littering.el" . 7690)
 ("/home/krisbalintona/main-emacs/straight/repos/evil/evil-vars.el" . 66429)
 ("/home/krisbalintona/main-emacs/configs/undoing.el" . 230)
 ("/home/krisbalintona/main-emacs/data/eshell/aliases" . 339)
 ("/usr/share/emacs/28.0.50/lisp/eshell/em-term.el" . 2052)
 ("/usr/share/emacs/28.0.50/lisp/eshell/em-hist.el" . 3813)
 ("/home/krisbalintona/main-emacs/straight/repos/eyebrowse/eyebrowse.el" . 3221)
 ("/home/krisbalintona/dotfiles/zsh/zsh/.zshrc" . 2303)
 ("/home/krisbalintona/main-emacs/configs/org-agenda.org" . 2350)
 ("/home/krisbalintona/main-emacs/straight/repos/helpful/helpful.el" . 2790)
 ("/home/krisbalintona/main-emacs/straight/repos/disable-mouse/disable-mouse.el" . 4556)
 ("/home/krisbalintona/.config/rofi/themes/dt-center.rasi" . 1533)
 ("/home/krisbalintona/dotfiles/i3/.local/bin/other/toggle_half_cores.sh" . 94)
 ("/home/krisbalintona/.local/bin/other/internal-keyboard-toggle.sh" . 260)
 ("/home/krisbalintona/main-emacs/straight/repos/rainbow-mode/rainbow-mode.el" . 39836)
 ("/home/krisbalintona/main-emacs/straight/repos/flimenu/flimenu.el" . 1838)
 ("/home/krisbalintona/main-emacs/straight/build/flimenu/flimenu-autoloads.el" . 1584)
 ("/usr/share/emacs/28.0.50/lisp/progmodes/js.el" . 52781)
 ("/home/krisbalintona/main-emacs/straight/repos/selectrum/selectrum.el" . 3300)
 ("/home/krisbalintona/Cloned_Repos/chemacs/.emacs" . 7023)
 ("/usr/share/emacs/28.0.50/lisp/vc/vc-git.el" . 75229)
 ("/home/krisbalintona/.config/rofi/config" . 83)
 ("/home/krisbalintona/.local/share/rofi/themes/dmenu.rasi" . 241)
 ("/home/krisbalintona/dotfiles/zsh/zsh/starship.toml" . 102)
 ("/home/krisbalintona/main-emacs/straight/repos/company-box/company-box.el" . 6119)
 ("/home/krisbalintona/main-emacs/straight/repos/outshine/outshine.el" . 21396)
 ("/home/krisbalintona/main-emacs/straight/repos/projectile/projectile.el" . 7589)
 ("/home/krisbalintona/main-emacs/straight/repos/org-roam/org-roam-completion.el" . 1479)
 ("/usr/share/emacs/28.0.50/lisp/outline.el" . 8119)
 ("/home/krisbalintona/main-emacs/configs/base-config.el" . 43)
 ("/home/krisbalintona/debug-emacs/config.org" . 115741)
 ("/home/krisbalintona/main-emacs/configs/org-packages.org" . 65)
 ("/home/krisbalintona/main-emacs/elisp/company-org-block.el" . 224)
 ("/home/krisbalintona/main-emacs/straight/repos/smartparens/smartparens.el" . 376103)
 ("/home/krisbalintona/main-emacs/straight/repos/org/lisp/org-src.el" . 9069)
 ("/usr/share/emacs/28.0.50/lisp/battery.el" . 7774)
 ("/usr/share/emacs/28.0.50/lisp/display-line-numbers.el" . 1453)
 ("/usr/share/emacs/28.0.50/lisp/epg-config.el" . 2825)
 ("/home/krisbalintona/Documents/org-database/"
  (dired-filename . "/home/krisbalintona/Documents/org-database/latex"))
 ("/home/krisbalintona/Documents/org-database/latex/POBS0910-niccolo-machiavelli.tex" . 964)
 ("/home/krisbalintona/Documents/org-database/latex/template-mla.tex" . 1246)
 ("/home/krisbalintona/main-emacs/straight/repos/org-roam-server/org-roam-server.el" . 6189)
 ("/home/krisbalintona/qmk_firmware/keyboards/kbdfans/kbd4x/keymaps/my-programmed-keymap/tapdance.c" . 9129)
 ("/home/krisbalintona/main-emacs/configs/qol-packages.el" . 10384)
 ("/home/krisbalintona/main-emacs/straight/build/consult/consult-autoloads.el" . 4356)
 ("/home/krisbalintona/main-emacs/straight/build/org-msg/org-msg-autoloads.el" . 964)
 ("/home/krisbalintona/main-emacs/straight/build/projectile/projectile-autoloads.el" . 20951)
 ("/home/krisbalintona/main-emacs/straight/build/counsel/counsel-autoloads.el" . 16950)
 ("/home/krisbalintona/main-emacs/straight/build/swiper/swiper-autoloads.el" . 1223)
 ("/home/krisbalintona/main-emacs/straight/build/ivy/ivy-autoloads.el" . 5141)
 ("/home/krisbalintona/main-emacs/straight/build/transient/transient-autoloads.el" . 2468)
 ("/home/krisbalintona/main-emacs/straight/build/anzu/anzu-autoloads.el" . 2291)
 ("/home/krisbalintona/main-emacs/data/abbrev.el" . 227)
 ("/home/krisbalintona/Documents/org-database/roam/bibliographic/master-lib.bib" . 6841)
 ("/home/krisbalintona/Documents/org-database/roam/bibliographic/master-lib-temp.bib" . 1503)
 ("/home/krisbalintona/main-emacs/straight/repos/auctex/tex-buf.el" . 37737)
 ("/home/krisbalintona/main-emacs/straight/repos/auctex/tex.el" . 66055)
 ("/home/krisbalintona/main-emacs/straight/repos/magic-latex-buffer/magic-latex-buffer.el" . 3029)
 ("/home/krisbalintona/main-emacs/straight/build/magic-latex-buffer/magic-latex-buffer-autoloads.el" . 888)
 ("/usr/share/emacs/28.0.50/lisp/textmodes/reftex-vars.el" . 55383)
 ("/home/krisbalintona/main-emacs/straight/build/auto-dictionary/auto-dictionary-autoloads.el" . 1347)
 ("/home/krisbalintona/main-emacs/straight/build/company-auctex/company-auctex-autoloads.el" . 1107)
 ("/home/krisbalintona/main-emacs/straight/repos/org/lisp/ox-latex.el" . 38605)
 ("/usr/share/emacs/28.0.50/lisp/textmodes/tex-mode.el" . 82017)
 ("/home/krisbalintona/main-emacs/straight/build/exec-path-from-shell/exec-path-from-shell-autoloads.el" . 1275)
 ("/home/krisbalintona/main-emacs/var/flyspell/flyspell-ispell-personal-dict-en" . 23)
 ("/home/krisbalintona/main-emacs/straight/repos/flyspell-lazy/flyspell-lazy.el" . 8378)
 ("/home/krisbalintona/main-emacs/straight/build/flyspell-correct-helm/flyspell-correct-helm-autoloads.el" . 331)
 ("/home/krisbalintona/main-emacs/var/spell-fu/"
  (dired-filename . "/home/krisbalintona/main-emacs/var/spell-fu/spell-fu-ispell-personal-dict-en"))
 ("/home/krisbalintona/main-emacs/elisp/"
  (dired-filename . "/home/krisbalintona/main-emacs/elisp/.."))
 ("/home/krisbalintona/main-emacs/configs/"
  (dired-filename . "/home/krisbalintona/main-emacs/configs/.."))
 ("/home/krisbalintona/main-emacs/straight/build/flyspell-lazy/flyspell-lazy-autoloads.el" . 2032)
 ("/home/krisbalintona/main-emacs/straight/build/flyspell-correct-popup/flyspell-correct-popup-autoloads.el" . 562)
 ("/home/krisbalintona/main-emacs/straight/build/flyspell-correct-avy-menu/flyspell-correct-avy-menu-autoloads.el" . 577)
 ("/home/krisbalintona/main-emacs/straight/build/avy-menu/avy-menu-autoloads.el" . 1066)
 ("/usr/share/emacs/28.0.50/lisp/textmodes/text-mode.el" . 1183)
 ("/usr/share/emacs/28.0.50/lisp/textmodes/ispell.el" . 12748)
 ("/home/krisbalintona/main-emacs/straight/repos/emacs-spell-fu/spell-fu.el" . 1918)
 ("/home/krisbalintona/main-emacs/straight/repos/auctex-latexmk/auctex-latexmk.el" . 2509)
 ("/home/krisbalintona/main-emacs/straight/repos/outorg/outorg.el" . 9362)
 ("/home/krisbalintona/main-emacs/straight/build/outshine/outshine-autoloads.el" . 910)
 ("/home/krisbalintona/main-emacs/straight/build/outorg/outorg-autoloads.el" . 1031)
 ("/home/krisbalintona/main-emacs/straight/repos/emacs-which-key/which-key.el" . 2080)
 ("/home/krisbalintona/main-emacs/straight/build/auctex-latexmk/auctex-latexmk-autoloads.el" . 431)
 ("/home/krisbalintona/main-emacs/straight/build/vterm-toggle/vterm-toggle-autoloads.el" . 1060)
 ("/home/krisbalintona/main-emacs/straight/build/vterm/vterm-autoloads.el" . 1115)
 ("/home/krisbalintona/main-emacs/straight/build/elisp-demos/elisp-demos-autoloads.el" . 432)
 ("/home/krisbalintona/main-emacs/straight/build/prettier/prettier-autoloads.el" . 2398)
 ("/home/krisbalintona/main-emacs/straight/build/flycheck/flycheck-autoloads.el" . 10385)
 ("/home/krisbalintona/main-emacs/straight/build/magit/magit-autoloads.el" . 85059)
 ("/home/krisbalintona/main-emacs/straight/build/git-commit/git-commit-autoloads.el" . 1664)
 ("/home/krisbalintona/main-emacs/straight/build/doom-snippts/doom-snippts-autoloads.el" . 623)
 ("/home/krisbalintona/main-emacs/straight/build/markdown-mode/markdown-mode-autoloads.el" . 1404)
 ("/home/krisbalintona/main-emacs/straight/build/spinner/spinner-autoloads.el" . 2380)
 ("/home/krisbalintona/main-emacs/straight/build/helm-org-rifle/helm-org-rifle-autoloads.el" . 1669)
 ("/home/krisbalintona/main-emacs/straight/build/org-roam-bibtex/org-roam-bibtex-autoloads.el" . 11530)
 ("/home/krisbalintona/main-emacs/straight/build/org-ref/org-ref-autoloads.el" . 31462)
 ("/home/krisbalintona/main-emacs/straight/build/helm-bibtex/helm-bibtex-autoloads.el" . 1184)
 ("/home/krisbalintona/main-emacs/straight/build/ivy-bibtex/ivy-bibtex-autoloads.el" . 1001)
 ("/home/krisbalintona/main-emacs/straight/build/bibtex-completion/bibtex-completion-autoloads.el" . 1351)
 ("/home/krisbalintona/main-emacs/straight/build/org-roam-server/org-roam-server-autoloads.el" . 1301)
 ("/home/krisbalintona/main-emacs/straight/build/org-ql/org-ql-autoloads.el" . 3044))
