;; -*- mode: emacs-lisp; coding: utf-8-unix -*-
;; Minibuffer history file, automatically generated by ‘savehist’.

(setq savehist-minibuffer-history-variables '(ivy-bibtex-history counsel-git-grep-history counsel-describe-symbol-history file-name-history minibuffer-history counsel-M-x-history))
(setq ivy-bibtex-history '(#("canto" 0 5 (ivy-index 0)) "🖋 🖇 White, Landeg The Lusiads, Canto V book whiteLusiadsCanto"))
(setq counsel-git-grep-history '(#("org-noter" 0 9 (ivy-index 0)) "configs/second-brain.org:307:** Org-noter"))
(setq counsel-describe-symbol-history '(#("noter doc hook" 0 14 (ivy-index 0)) "org-noter-doc-mode-hook"))
(setq file-name-history '("~/main-emacs/configs/second-brain.org" "~/Documents/org-database/roam/Oct312020-140749-whitelusiadscanto.org" "~/Documents/org-database/agenda/inbox.org" "~/qmk_firmware/keyboards/kbdfans/kbd4x/keymaps/my-programmed-keymap/tapdance.c" "~/main-emacs/configs/evil-packages.org" "~/Documents/org-database/roam/Oct292020-130117.org" "~/Documents/Emails/Queue/cur/2020-11-01_19:12:46_1" "~/qmk_firmware/keyboards/kbdfans/kbd4x/keymaps/my-programmed-keymap/keymap.c" "~/main-emacs/configs/base-config.org" "~/main-emacs/configs/shell.org" "~/main-emacs/configs/completion-frameworks.org" "~/main-emacs/straight/build/golden-ratio/golden-ratio-autoloads.el" "~/main-emacs/elisp/better-defaults-rcp.el" "~/main-emacs/elisp/straight-package-management-rcp.el"))
(setq minibuffer-history '("Letter of Pero Vaz de Caminha Notes - Oct292020-125345-caminhaletterperovaz.org" #("(bib, document) caminhaLetterPeroVaz: Letter of Pero Vaz de Caminha" 0 16 (face org-roam-tag))))
(setq counsel-M-x-history '(#("kill session" 0 12 (ivy-index 0)) "org-noter-kill-session" #("find-file" 0 9 (ivy-index 2))))
(setq evil-jumps-history 'nil)
